name: Build and upload assets
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, windows-latest, macos-latest]
    name: Building, ${{ matrix.os }}
    steps:

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc

      - name: Create bin directory
        run: mkdir bin

      - name: Build on Linux GNU
        if: matrix.os == 'ubuntu-20.04'

        # We're using musl to make the binaries statically linked and portable.
        run: |
          cargo build --target=x86_64-unknown-linux-gnu --release
          archive="bin/spectre-miner-${{ github.event.release.tag_name }}-linux-gnu-amd64.zip"
          asset_name="spectre-miner-${{ github.event.release.tag_name }}-linux-gnu-amd64"
          strip ./target/x86_64-unknown-linux-gnu/release/spectre-miner
          mv ./target/x86_64-unknown-linux-gnu/release/spectre-miner ./bin/${asset_name}
          zip -r "${archive}" ./bin/${asset_name}
          rm ./bin/${asset_name}

      - name: Build on Linux musl
        if: matrix.os == 'ubuntu-latest'

        # We're using musl to make the binaries statically linked and portable.
        run: |
          sudo apt-get install -y musl-tools
          rustup target add x86_64-unknown-linux-musl
          cargo build --target=x86_64-unknown-linux-musl --release
          archive="bin/spectre-miner-${{ github.event.release.tag_name }}-linux-musl-amd64.zip"
          asset_name="spectre-miner-${{ github.event.release.tag_name }}-linux-musl-amd64"
          strip ./target/x86_64-unknown-linux-musl/release/spectre-miner
          mv ./target/x86_64-unknown-linux-musl/release/spectre-miner ./bin/${asset_name}
          zip -r "${archive}" ./bin/${asset_name}
          rm ./bin/${asset_name}

      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        shell: bash

        # We're using 'bin/' instead of './bin/' as otherwise 7z won't add the directory.
        run: |
          cargo build --target=x86_64-pc-windows-msvc --release
          archive="bin/spectre-miner-${{ github.event.release.tag_name }}-win64-amd64.zip"
          asset_name="spectre-miner-${{ github.event.release.tag_name }}-win64-amd64.exe"
          mv ./target/x86_64-pc-windows-msvc/release/spectre-miner.exe ./bin/${asset_name}
          7z a -tzip -r "${archive}" bin/${asset_name}
          rm ./bin/${asset_name}

      - name: Build on MacOS for x86_64
        if: matrix.os == 'macos-latest'
        run: |
          rustup target add x86_64-apple-darwin
          cargo build --target=x86_64-apple-darwin --release
          archive="bin/spectre-miner-${{ github.event.release.tag_name }}-osx-amd64.zip"
          asset_name="spectre-miner-${{ github.event.release.tag_name }}-osx-amd64"
          mv ./target/x86_64-apple-darwin/release/spectre-miner ./bin/${asset_name}
          zip -r "${archive}" ./bin/${asset_name}
          rm ./bin/${asset_name}

      - name: Build on MacOS for M1/2
        if: matrix.os == 'macos-latest'
        run: |
          cargo build --target=aarch64-apple-darwin --release
          archive="bin/spectre-miner-${{ github.event.release.tag_name }}-osx-aarch64.zip"
          asset_name="spectre-miner-${{ github.event.release.tag_name }}-osx-aarch64"
          mv ./target/aarch64-apple-darwin/release/spectre-miner ./bin/${asset_name}
          zip -r "${archive}" ./bin/${asset_name}
          rm ./bin/${asset_name}

      - name: Upload release asset
        uses: softprops/action-gh-release@v2.0.6
        with:
          files: |
            bin/*
